### ISSUE TITLE
Add function to determine if the CT poison extension is present

### ISSUE THREAD

**Issue by titanous** [crtsh/libx509pq#2]
This is useful if a query wants to look for a corresponding issued certificate (or vice versa).

**Comment by titanous** [comment]
@alex says:

> Probably the easiest way to implement that is a generic `x509HasExtension` API.

**Comment by robstradling** [comment]
Good idea.  I'll add that.

**Comment by robstradling** [comment]
Addressed by https://github.com/crtsh/libx509pq/commit/a9ff1250e0cd8863389146b37935687b5446fb20
