### ISSUE TITLE
SELECT x509_*(c.certificate) does not work

### ISSUE THREAD

**Issue by bedford1234** [crtsh/libx509pq#6]
Hello @robstradling ,

I'm trying to use SELECT x509_*(c.certificate) in my sql query to retrieve all of the functions in the crtsh db. However that command does not work. Does anyone have a solution to why it is not working? I would greatly appreciate your help!

**Comment by bedford1234** [comment]
Hello @robstradling ,

I'm trying to use SELECT x509_*(c.certificate) in my sql query to retrieve all of the functions in the crtsh db. However that command does not work. Does anyone have a solution to why it is not working? I would greatly appreciate your help!

**Comment by robstradling** [comment]
Try typing `\df` at your psql prompt.

**Comment by bedford1234** [comment]
@robstradling Thanks for your response. So you are saying to do add /df to psql -h crt.sh -p 5432 -U guest certwatch \df. If so, I get an message saying extra argument ignored?

**Comment by robstradling** [comment]
No.  Type `psql -h crt.sh -p 5432 -U guest certwatch`.  Then press ENTER.  Then, at the "certwatch=>" prompt, type `\df`.

**Comment by bedford1234** [comment]
@robstradling Thank you for your help! I tried that an I got the schema for the db. How do I select all of the fields using the *?

**Comment by robstradling** [comment]
https://stackoverflow.com/questions/1347282/how-can-i-get-a-list-of-all-functions-stored-in-the-database-of-a-particular-sch provides the underlying SELECT query that `\df` uses.

**Comment by bedford1234** [comment]
@robstradling Thanks again for your help! I tried \df certificate identities.* and it doesn't work

**Comment by robstradling** [comment]
"fields in the table"?  What table?

You asked how to "retrieve all of the functions".  A function is not a table.
